trigger:
  branches:
    include:
      - main
      - function/*

pr:
  branches:
    include:
      - main
      - function/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  PYTHON_VERSION: '3.11'
  NODE_VERSION: '18.x'
  BACKEND_DIR: 'backend'
  FRONTEND_DIR: 'frontend'

stages:
- stage: backend_ci
  displayName: Backend CI
  jobs:
  - job: backend
    steps:
    - task: UsePythonVersion@0
      inputs: { versionSpec: '$(PYTHON_VERSION)', architecture: 'x64' }

    - script: |
        python -m pip install --upgrade pip
        pip install -r $(BACKEND_DIR)/requirements.txt || \
          pip install fastapi uvicorn[standard] pydantic requests PyYAML flake8 pytest
      displayName: Install Python deps

    - script: |
        cd $(BACKEND_DIR)
        flake8 app || true
      displayName: Lint (flake8)

    - script: |
        echo "Add pytest later (backend/tests). Skipping for now."
      displayName: Tests (placeholder)

- stage: frontend_build
  displayName: Frontend build
  dependsOn: backend_ci
  jobs:
  - job: build_frontend
    steps:
    - task: NodeTool@0
      inputs: { versionSpec: '$(NODE_VERSION)' }

    - script: |
        cd $(FRONTEND_DIR)
        npm ci
        npm run build
      displayName: Install & build (Vite)

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(FRONTEND_DIR)/dist'
        artifactName: 'frontend-dist'
        publishLocation: 'Container'
      displayName: Publish dist as artifact
