checks:
  - name: Router HTTP
    port: 80
    protocol: http
    severity: warning
    advice: "Your router’s HTTP port appears reachable. Consider disabling remote admin or using HTTPS only."

  - name: HTTPS
    port: 443
    protocol: https
    severity: info
    advice: "Standard HTTPS port reachable."

  - name: Telnet
    port: 23
    protocol: tcp
    severity: issue
    advice: "Telnet is insecure. Disable Telnet access on your router."